### PR TITLE
Lacosmicx

### PR DESCRIPTION
**Pull request by cmccully**
I have finished the optimized LA Cosmic implementation. It uses Cython for the main part of the algorithm and uses C for the individual routines. Everything is multithreaded using OpenMP (the Cython standard). For a 4K x 2K image, this implementation is ~35 times faster than cosmics.py written by Malte Tewes (which is already significantly faster than the original IRAF version). 

Given the complexity of this code, should this be included in imageutils or should it be its own package? 

Any other comments are welcome.

### CODE REVIEW

**Comment by larrybradley** [comment]
Any updates on the licensing issue?

**Comment by cmccully** [comment]
The travis build now fails for two of the tests saying jinja2 is not installed. I think I am using the most up to date build of imageutils master. Anyone know how to fix this? Thanks.

**Comment by astrofrog** [comment]
@cmccully - in the file ``.travis.yml`` there is a line that says:

```
- if [[ $SETUP_CMD != egg_info ]]; then $CONDA_INSTALL numpy=$NUMPY_VERSION pytest pip Cython; fi
```

add ``jinja2`` just after ``Cython``, so:

```
- if [[ $SETUP_CMD != egg_info ]]; then $CONDA_INSTALL numpy=$NUMPY_VERSION pytest pip Cython jinja2; fi
```

basically ``jinja2`` is now required to build the developer version of Astropy.

**Comment by astrofrog** [comment]
@eteq - any updates on the licensing issue?

**Comment by mwcraig** [comment]
@eteq @astrofrog -- friendly bump...we are waiting for this to land somewhere so we remove functionality that duplicates this (but runs much more slowly) in ccdproc

**Comment by larrybradley** [comment]
lacosmic is now in the `astroscrappy` package.

**Pull request closed without merging**
